name: GitHub Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: platane/snk@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: therealltre

      - name: Commit and push SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mv github-contribution-grid-snake.svg ../github-contribution-grid-snake.svg || true
          git add ../github-contribution-grid-snake.svg
          git commit -m "Update contribution snake" || echo "No changes to commit"
          git push origin main
